### ISSUE TITLE
Firefox rendering

### ISSUE THREAD

**Issue by rcmiller** [uid/snapdown#14]
Try this in Firefox:
https://web.mit.edu/dwhatley/www/snapdown/web/production.html#xyz%20-%3E%20(String%20)

The String class name is at the wrong y coordinate.  Looks ok in Chrome.

**Comment by dwhatley19** [comment]
Fixed by setting the `dominant-baseline` attribute for all `text` elements. Text elements in Firefox are still _slightly_ different from those in Chrome (a few pixels to the left), but I'm guessing this falls under a larger browser compatibility issue.
