### ISSUE TITLE
Double-arrows sometimes do not show

### ISSUE THREAD

**Issue by dwhatley19** [uid/snapdown#9]
Double (immutable) arrows sometimes do not show, as in the following example:
```
a => (String "a")
b => a
c => b
```
which current produces this diagram:
<img width="100" alt="Screen Shot 2020-08-02 at 2 10 09 PM" src="https://user-images.githubusercontent.com/5375330/89132565-f577b700-d4c9-11ea-9760-85d55faa8a7b.png">

Direct URL: https://web.mit.edu/dwhatley/www/snapdown/web/production.html#a%20%3D%3E%20(String%20%22a%22)%0Ab%20%3D%3E%20a%0Ac%20%3D%3E%20b

It seems all three `path.snap-arrow.snap-immutable` elements are present, but only two of them are actually displaying in the SVG.

**Comment by maxg** [comment]
Safari shows the vertical arrow, but both Chrome and Safari fail for me on almost-vertical arrows:

[<img width="311" alt="image" src="https://user-images.githubusercontent.com/41432/89133674-d4c05900-d4eb-11ea-9794-25546dec8d8b.png">](https://web.mit.edu/dwhatley/www/snapdown/web/production.html#a%20%3D%3E%20(String%20%22aaaaaaaa%22)%0Ab%20-%3E%20a)

Seems like a bounding box clipping problem.

**Comment by dwhatley19** [comment]
Fixed by changing coordinates and size fields of the `filter` SVG element.
